package curso.exercicio.BatleAnime.AnimeTest;

import curso.exercicio.BatleAnime.AnimeClass.Bots;
import curso.exercicio.BatleAnime.AnimeClass.Personagens;
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class AnimeInterface extends javax.swing.JFrame {
        LutaInterface lt;
        Random gerador = new Random();
        Personagens Luffy = new Personagens("Luffy",19,"One Piece",100,200,300,10,10,5,1000);
        Personagens Goku = new Personagens("Goku",22,"DBZ",100,200,300,10,10,4,1000);
        Bots luffy = new Bots("Luffy",19,"One Piece",100,200,300,10,10,4,1000);
        Bots goku = new Bots("Goku",22,"DBZ",100,200,300,10,10,4,1000);
        Personagens per[] = (new Personagens[] {Luffy,Goku});
        Bots bot[] = (new Bots[] {luffy,goku});
        Personagens p1;
        Bots b1 = bot[gerador.nextInt(2)];
   
   
    /**
     * Creates new form AnimeInterface
     */
    public AnimeInterface() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("LUFFY");
        jButton1.setPreferredSize(new java.awt.Dimension(700, 973));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 130, 160, 160);
        ImageIcon icon = new ImageIcon("src/a1.png");
        icon.setImage(icon.getImage().getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), 1));
        jButton1.setIcon(icon);

        jButton2.setText("GOKU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 130, 150, 160);
        ImageIcon icon2 = new ImageIcon("src/b1.png");
        icon2.setImage(icon2.getImage().getScaledInstance(jButton2.getWidth(), jButton2.getHeight(), 1));
        jButton2.setIcon(icon2);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(140, 0, 90, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             per[0].setId(0);
        if(lt == null){
            lt = new LutaInterface();
            lt.Dados(per[0], b1); 
            lt.setVisible(true);
//            }else{
//            lt.setVisible(true);
//            lt.setState(LutaInterface.NORMAL);
//            lt.Dados(per[0], b1); 
        }
             setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            per[1].setId(1);     
            if(lt == null){
            lt = new LutaInterface();
            lt.Dados(per[1], b1);
            lt.setVisible(true);
            
             }
             setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    public  void main(String args[]) {
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimeInterface().setVisible(true);
            }
        });
    }

    public Random getGerador() {
        return gerador;
    }

    public void setGerador(Random gerador) {
        this.gerador = gerador;
    }

    public Personagens getLuffy() {
        return Luffy;
    }

    public void setLuffy(Personagens Luffy) {
        this.Luffy = Luffy;
    }

    public Personagens getGoku() {
        return Goku;
    }

    public void setGoku(Personagens Goku) {
        this.Goku = Goku;
    }



    public void setLuffy(Bots luffy) {
        this.luffy = luffy;
    }


    public void setGoku(Bots goku) {
        this.goku = goku;
    }

    public Personagens getP1() {
        return p1;
    }

    public void setP1(Personagens p1) {
        this.p1 = p1;
    }

    public Bots getB1() {
        return b1;
    }

    public void setB1(Bots b1) {
        this.b1 = b1;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
